annotate_aggregate/urls.py
from django.urls import path

from . import views

app_name = "annotate_aggregate"

urlpatterns = [
    path('store/', views.store, name='store'),
    path('store/book/<int:pk>/', views.store_in, name='store_in'),
    path('authors/', views.authors, name='authors'),
    path('authors/books/<int:pk>/', views.authors_in, name='authors_in'),

    path('publishers/', views.PublisherList.as_view(), name='publisher-list'),
    path('books/', views.BookList.as_view(), name='books-list'),

    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher-detail'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book-detail'),

    path('publisher/create/', views.PublisherCreate.as_view(), name='publisher-create'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),

    path('publisher/<int:pk>/update/', views.PublisherUpdate.as_view(), name='publisher-update'),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name='book-update'),

    path('publisher/<int:pk>/delete', views.PublisherDelete.as_view(), name='publisher-delete'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),

    path('contact_form/', views.contact_form, name='contact_form'),

]

dz12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('annotate_aggregate/', include('annotate_aggregate.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('mail/', include('mail.urls')),

]

mail/urls.py
from django.urls import path

from . import views

app_name = "mail"

urlpatterns = [
    path('send_mail/', views.send_mail, name='send_mail')
]

annotate_aggregate/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return f"{self.name}"


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pubdate = models.DateField()

    def __str__(self):
        return f"{self.name}, {self.publisher}"


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name

pars/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.CharField(max_length=165)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.quote

annotate_aggregate/forms.py
from django import forms


class Mail(forms.Form):
    mail = forms.EmailField(label='You email')
    text = forms.CharField(widget=forms.Textarea(attrs={"rows": "10"}))

annotate_aggregate/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Avg, Count
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page

from .forms import Mail
from .models import Author, Book, Publisher, Store
from .tasks import send_mail


def store(request):
    store_list = Store.objects.prefetch_related('books').all()
    paginator = Paginator(store_list, 5)
    page_number = request.GET.get('page')
    store_list = paginator.get_page(page_number)
    return render(request, 'annotate_aggregate/store.html', {'store_list': store_list})


@cache_page(10)
def store_in(request, pk):
    books = Book.objects.select_related('publisher').prefetch_related('authors').filter(pk=pk)
    return render(request, 'annotate_aggregate/store_in.html', {'book': books})


@cache_page(10)
def authors(request):
    author = Author.objects.all().annotate(num=Count('book'))
    paginator = Paginator(author, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'annotate_aggregate/authors.html', {'page_obj': page_obj})


@cache_page(10)
def authors_in(request, pk):
    author = get_object_or_404(Author, pk=pk)
    books = author.book_set.all()
    avg = author.book_set.aggregate(a=Avg('price'))
    return render(request, 'annotate_aggregate/authors_in.html', {'books': books, 'avg': avg.get('a')})


@method_decorator(cache_page(10), name='dispatch')
class PublisherList(generic.ListView):
    model = Publisher
    paginate_by = 5
    template_name = 'annotate_aggregate/publisher_list.html'
    queryset = Publisher.objects.annotate(num_books=Count('book'))


@method_decorator(cache_page(10), name='dispatch')
class BookList(generic.ListView):
    model = Book
    paginate_by = 100
    template_name = 'annotate_aggregate/book_list.html'


@method_decorator(cache_page(10), name='dispatch')
class PublisherDetail(generic.DetailView):
    model = Publisher
    context_object_name = 'pub_list'
    template_name = 'annotate_aggregate/publisher_detail.html'


@method_decorator(cache_page(10), name='dispatch')
class BookDetail(generic.DetailView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'annotate_aggregate/book_detail.html'


class PublisherCreate(LoginRequiredMixin, generic.CreateView):
    model = Publisher
    fields = ['name']
    template_name = 'annotate_aggregate/publisher_create.html'

    def get_success_url(self):
        return reverse('annotate_aggregate:publisher-detail', kwargs={'pk': self.object.id})


class BookCreate(LoginRequiredMixin, generic.CreateView):
    model = Book
    fields = ['name', 'pages', 'rating', 'price', 'authors', 'publisher', 'pubdate']
    template_name = 'annotate_aggregate/book_create.html'

    def get_success_url(self):
        return reverse('annotate_aggregate:book-detail', kwargs={'pk': self.object.id})


class PublisherUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Publisher
    fields = ['name']
    template_name = 'annotate_aggregate/publisher_update.html'

    def get_success_url(self):
        return reverse('annotate_aggregate:publisher-detail', kwargs={'pk': self.object.id})


class BookUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Book
    fields = ['name', 'pages', 'rating', 'price', 'authors', 'publisher', 'pubdate']
    template_name = 'annotate_aggregate/book_update.html'

    def get_success_url(self):
        return reverse('annotate_aggregate:book-detail', kwargs={'pk': self.object.id})


class PublisherDelete(LoginRequiredMixin, generic.DeleteView):
    model = Publisher
    template_name = 'annotate_aggregate/publisher_delete.html'
    success_url = reverse_lazy('publisher-list')

    def get_success_url(self):
        return reverse('annotate_aggregate:publisher-list')


class BookDelete(LoginRequiredMixin, generic.DeleteView):
    model = Book
    template_name = 'annotate_aggregate/book_delete.html'
    success_url = reverse_lazy('books-list')

    def get_success_url(self):
        return reverse('annotate_aggregate:books-list')


def contact_form(request):
    data = dict()
    if request.method == "POST":
        form = Mail(request.POST)
        if form.is_valid():
            data['form_is_valid'] = True
            to_mail = form.cleaned_data['mail']
            text = form.cleaned_data['text']
            subject = 'Someone need your help'
            send_mail.delay(subject, text, to_mail)
        else:
            data['form_is_valid'] = False
    else:
        form = Mail()
    context = {'form': form}
    data['html_form'] = render_to_string('annotate_aggregate/contact_form.html', context, request=request)
    return JsonResponse(data)

annotate_aggregate/templates/annotate_aggregate/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
<li><a href="{% url 'annotate_aggregate:store'%}">To all Store </a></li>
<li><a href="{% url 'annotate_aggregate:books-list'%}">To all Books </a></li>
<li><a href="{% url 'annotate_aggregate:publisher-list'%}">To all publisher </a></li>
{% if page_obj %}
    <ul>
    {% for i in page_obj %}
        <h3>Authors:</h3>
        <p><a href="{% url 'annotate_aggregate:authors_in' i.id %}"> {{ i.name }}</a><br> Age {{i.age}}</p>
        <p>Number of books: {{i.num}}</p>
    {% endfor %}
    </ul>
{% else %}
    <p>No author are available.</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/authors_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors info</title>
</head>
<body>
<li><a href="{% url 'annotate_aggregate:authors'%}">Back to all Authors </a></li>
<li><a href="{% url 'annotate_aggregate:store'%}">To all Store </a></li>
<li><a href="{% url 'annotate_aggregate:books-list'%}">To all Books </a></li>
<li><a href="{% url 'annotate_aggregate:publisher-list'%}">To all publisher </a></li>
{% if books %}

    <ul>
      <p>Decimal price - {{avg}}</p>
    {% for i in books %}
        <h3>Books:</h3>
        <p>{{i.name}}</p>
        <p>Price - {{i.price}}</p>
        <p>Rating - {{i.rating}}</p>
        <p>Pages - {{i.pages}}</p>
        <p><a href="{% url 'annotate_aggregate:publisher-detail' i.publisher.id %}">Publisher - {{ i.publisher.name }}</a></p>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/book_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Create"/>
  </form>
<ul>
<li><a href="{% url 'annotate_aggregate:publisher-list' %}"> Back to book list</a></li>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/book_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="DELETE">
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<a href="{% url 'annotate_aggregate:books-list' %}">Back to All Book</a>
<h1>Book title: {{ book_list.name }}</h1>
    {% if book_list %}
        <ul>
            <p>Price - {{book_list.price}}</p>
            <p>Rating - {{book_list.rating}}</p>
            <p> Pages - {{book_list.pages}}</p>
            <p> Pup date - {{book_list.pubdate}}</p>
            <p>Authors: {{ book_list.authors.all|join:", " }}.</p>
            <p>Publisher: <a href="{% url 'annotate_aggregate:publisher-detail' book_list.publisher.id%}">{{book_list.publisher}}</a></p>
        </ul>
    {% else %}
    <p>No book</p>
    {% endif %}
<li><a href="{% url 'annotate_aggregate:book-update' book_list.id %}">Book update</a></li>
<li><a href="{% url 'annotate_aggregate:book-delete' book_list.id %}">Book delete</a></li>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All book</title>
</head>
<body>
<h2>Books</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'annotate_aggregate:book-detail' book.id %}">{{ book.name }}</a></li>
            <p> {{book.num_books}}</p>
        {% endfor %}
    </ul>
{% if page_obj.has_previous %}
            <a href="?page=1">First page</a>&nbsp;
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>&nbsp;
            <a href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
        {% endif %}

<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<li><a href="{% url 'annotate_aggregate:publisher-list' %}">Back to Publisher list</a></li>
  <h1>Publisher name: {{ publisher.name }}</h1>
    {% if pub_list.book_set.all %}
        <ul>
        {% for pub in pub_list.book_set.all %}
            <li>Book:<a href="{% url 'annotate_aggregate:book-detail' pub.id %}">{{pub.name}}</a></li></li>
            <p>Rating - {{pub.rating}}</p>
        {% endfor %}
        </ul>
    {% else %}
    <p>The publisher has no books</p>
    {% endif %}
<li><a href="{% url 'annotate_aggregate:publisher-update' pub_list.id %}">Publisher update</a></li>
<li><a href="{% url 'annotate_aggregate:publisher-delete' pub_list.id %}">Publisher delete</a></li>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/publisher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Publisher</title>
</head>
<body>
<li><a href="{% url 'annotate_aggregate:publisher-create' %}"> Create Publisher</a></li>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'annotate_aggregate:publisher-detail' publisher.id %}">{{ publisher.name }}</a></li>
            <p>The number of published books {{publisher.num_books}}</p>
        {% endfor %}
    </ul>

{% if page_obj.has_previous %}
            <a href="?page=1">First page</a>&nbsp;
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>&nbsp;
            <a href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
        {% endif %}
<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
</body>
</html>

annotate_aggregate/templates/annotate_aggregate/store_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store info</title>
</head>
<body>
<a href="{% url 'annotate_aggregate:store'%}">Back to all Store </a></li>
<li><a href="{% url 'annotate_aggregate:authors'%}">To all Authors </a></li>
<li><a href="{% url 'annotate_aggregate:books-list'%}">To all Books </a></li>
<li><a href="{% url 'annotate_aggregate:publisher-list'%}">To all Publisher</a></li>
{% if book %}
    <ul>
    {% for i in book %}
        <h2>Book name: {{ i.name }}</h2>
            <p>Book info:</p>
            <p>Price - {{i.price}}</p>
            <p>Pages - {{i.pages}}</p>
            <p>Rating - {{i.rating}}</p>
            <p><a href="{% url 'annotate_aggregate:publisher-detail' i.publisher_id %}">Publisher {{ i.publisher.name }} </a></p>
        {% for b in i.authors.all %}
            <p><a href="{% url 'annotate_aggregate:authors_in' b.id %}">Author: {{ b.name }} - Age {{ b.age }} </a></p>
        {% endfor %}
    {% endfor %}
    </ul>
{% else %}
    <p>No book are available.</p>
{% endif %}
</body>
</html>

templates/annotate_aggregate/authors.html
{% extends "base.html" %}
{% block content %}
{% if page_obj %}
    <ul>
    {% for i in page_obj %}
        <h3>Authors:</h3>
        <p><a href="{% url 'annotate_aggregate:authors_in' i.id %}"> {{ i.name }}</a><br> Age {{i.age}}</p>
        <p>Number of books: {{i.num}}</p>
        <hr>
    {% endfor %}
    </ul>
{% else %}
    <p>No author are available.</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
{% endblock %}

templates/annotate_aggregate/authors_in.html
{% extends "base.html" %}
{% block content %}
<li><a href="{% url 'annotate_aggregate:authors'%}">Back to all Authors </a></li>

{% if books %}

    <ul>
      <p>Decimal price - {{avg}}</p>
    {% for i in books %}
        <h3>Books:</h3>
        <p>{{i.name}}</p>
        <p>Price - {{i.price}}</p>
        <p>Rating - {{i.rating}}</p>
        <p>Pages - {{i.pages}}</p>
        <p><a href="{% url 'annotate_aggregate:publisher-detail' i.publisher.id %}">Publisher - {{ i.publisher.name }}</a></p>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}
{% endblock %}

templates/annotate_aggregate/book_detail.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'annotate_aggregate:books-list' %}">Back to All Book</a>
<h1>Book title: {{ book_list.name }}</h1>
    {% if book_list %}
        <ul>
            <p>Price - {{book_list.price}}</p>
            <p>Rating - {{book_list.rating}}</p>
            <p> Pages - {{book_list.pages}}</p>
            <p> Pup date - {{book_list.pubdate}}</p>
            <p>Authors: {{ book_list.authors.all|join:", " }}.</p>
            <p>Publisher: <a href="{% url 'annotate_aggregate:publisher-detail' book_list.publisher.id%}">{{book_list.publisher}}</a></p>
        </ul>
    {% else %}
    <p>No book</p>
    {% endif %}
<li><a href="{% url 'annotate_aggregate:book-update' book_list.id %}">Book update</a></li>
<li><a href="{% url 'annotate_aggregate:book-delete' book_list.id %}">Book delete</a></li>
{% endblock %}

templates/annotate_aggregate/contact_form.html
{% block content %}
<form method="post" action="{% url 'annotate_aggregate:contact_form' %}" class="js-send-mail-form">
  {% csrf_token %}
    <div class="modal-header">
        <h4 class="modal-title">Contact us</h4>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
     {{ form.as_p}}
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Contact us</button>
    </div>
</form>
{% endblock %}

templates/annotate_aggregate/publisher_detail.html
{% extends "base.html" %}
{% block content %}
<li><a href="{% url 'annotate_aggregate:publisher-list' %}">Back to Publisher list</a></li>
  <h1>Publisher name: {{ publisher.name }}</h1>
    {% if pub_list.book_set.all %}
        <ul>
        {% for pub in pub_list.book_set.all %}
            <li>Book:<a href="{% url 'annotate_aggregate:book-detail' pub.id %}">{{pub.name}}</a></li></li>
            <p>Rating - {{pub.rating}}</p>
        {% endfor %}
        </ul>
    {% else %}
    <p>The publisher has no books</p>
    {% endif %}
<li><a href="{% url 'annotate_aggregate:publisher-update' pub_list.id %}">Publisher update</a></li>
<li><a href="{% url 'annotate_aggregate:publisher-delete' pub_list.id %}">Publisher delete</a></li>
{% endblock %}

templates/annotate_aggregate/publisher_list.html
{% extends "base.html" %}
{% block content %}
<li><a href="{% url 'annotate_aggregate:publisher-create' %}"> Create Publisher</a></li>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'annotate_aggregate:publisher-detail' publisher.id %}">{{ publisher.name }}</a></li>
            <p>The number of published books {{publisher.num_books}}</p>
        {% endfor %}
    </ul>

{% if page_obj.has_previous %}
            <a href="?page=1">First page</a>&nbsp;
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>&nbsp;
            <a href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
        {% endif %}
<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
{% endblock %}

templates/annotate_aggregate/store.html
{% extends "base.html" %}
{% block content %}
<h1>STORE</h1>
{% if store_list %}
    <ul>
        <h2>Store name: </h2>
    {% for store in store_list %}
        <h3>{{ store.name }}</h3>
        <h3> Store books:</h3>
            {% for i in store.books.all %}
            <li><a href="{% url 'annotate_aggregate:store_in' i.id %}"> {{ i.name }} </a></li>
                <p> Price - {{ i.price}} </p>
            {% endfor %}
    {% endfor %}
    </ul>
{% else %}
    <p>No store are available.</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if store_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ store_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ store_list.number }} of {{ store_list.paginator.num_pages }}.
        </span>

        {% if store_list.has_next %}
            <a href="?page={{ store_list.next_page_number }}">next</a>
            <a href="?page={{ store_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<form action="." method="get">
    <label>Page number<input type="text" name="page"></label>
    <input type="submit">
</form>
{% endblock %}

templates/annotate_aggregate/store_in.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'annotate_aggregate:store'%}">Back to all Store </a></li>
{% if book %}
    <ul>
    {% for i in book %}
        <h2>Book name: {{ i.name }}</h2>
            <p>Book info:</p>
            <p>Price - {{i.price}}</p>
            <p>Pages - {{i.pages}}</p>
            <p>Rating - {{i.rating}}</p>
            <p><a href="{% url 'annotate_aggregate:publisher-detail' i.publisher_id %}">Publisher {{ i.publisher.name }} </a></p>
        {% for b in i.authors.all %}
            <p><a href="{% url 'annotate_aggregate:authors_in' b.id %}">Author: {{ b.name }} - Age {{ b.age }} </a></p>
        {% endfor %}
    {% endfor %}
    </ul>
{% else %}
    <p>No book are available.</p>
{% endif %}
{% endblock %}

templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
             integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
             crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block extra_js %}
  <script src="{% static '/js/send_mail.js' %}"></script>
{% endblock %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
        <div class="sidebar-nav">
            <div class="sidebar-nav">
                <li><a href="{% url 'annotate_aggregate:store'%}">To all Store. </a></li>
                <li><a href="{% url 'annotate_aggregate:books-list'%}">To all Books. </a></li>
                <li><a href="{% url 'annotate_aggregate:publisher-list'%}">To all Publisher. </a></li>
                <li><a href="{% url 'annotate_aggregate:authors'%}">To all Authors. </a></li>
                <hr>
                <p>
                <button type="button" class="btn btn-primary js-send-mail" data-url="{% url 'annotate_aggregate:contact_form' %}">
                <span class="glyphicon glyphicon-plus"></span>
                    Contact us
                </button>
                </p>
            </div>
        </div>
    </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}
      </div>
  </div>
</div>
<div class="modal fade" id="modal-mail" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">

    </div>
  </div>
</div>
<div class="modal fade" id="modal-contact">
  <div class="modal-dialog">
    <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Messages</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Your message has been sent to an administrator!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
    </div>
  </div>
</div>

</body>
</html>